routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('meetingtasks/donet/{id}', 'TopicController@donet')->name('donet');
Route::get('tasks/done/{id}', 'TaskController@done')->name('done');
Route::resource('/meetings','MeetingController')->middleware('auth');
Route::resource('meeting', 'MeetingController');
Route::post('meeting/store', 'MeetingController@store')->name('store');
Route::get('meeting/create', 'MeetingController@create')->name('create');
Route::resource('/users','UserController')->middleware('auth');
Route::resource('users', 'UserController');
Route::resource('/organizations','OrganizationController')->middleware('auth');
Route::resource('organizations', 'OrganizationController');
Route::resource('/profile','ProfileController')->middleware('auth');
Route::resource('profile', 'ProfileController');
Route::put('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@update']);
Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
Route::put('organizations', ['as' => 'organizations.edit', 'uses' => 'OrganizationController@update']);
Route::put('organizations', ['as' => 'organizations.update', 'uses' => 'OrganizationController@update']);


Route::get('tasks/meetingTasks/{meeting_id}','TaskController@meetingTasks')->name('meetingTasks');
Route::get('/neworg', function () { return view('neworg');})->name('neworg');
Route::resource('meeting', 'MeetingController');
Route::resource('organization', 'ProfileController');
Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::put('organization', ['as' => 'organizations.edit', 'uses' => 'OrganizationController@update']);
	Route::put('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@update']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('user', ['as' => 'users.edit', 'uses' => 'UserController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	Route::get('editmin', 'UserController@editOrg')->name('editMin');
	Route::put('editMin', 'UserController@updateOrg')->name('updateOrg');
});

Route::post('/tasks/{meeting_id?}','TaskController@store')->name('store');
Route::post('/topics-store/{meeting_id?}','TopicController@store')->name('topics-store');

Route::resource('/meetings','MeetingController')->middleware('auth');
Route::resource('/tasks','TaskController')->except(['store']);
Route::resource('/topics','TopicController')->except(['store']);
Route::get('tasks/{meeting_id}','TaskController@store');
Route::get('topics/{meeting_id}','TopicController@store');

//didint go over yet
Route::group(['middleware' => 'auth'], function () {
	//Route::get('table-list', 'MeetingController@index')->name('table');
	Route::get('/dashboard', 'MeetingController@dashboard')->name('dashboard');
	Route::get('passed_meetings', 'MeetingController@passed')->name('passed_meetings');
	Route::get('notifications', 'MeetingController@tasks')->name('notifications');
	Route::get('/meetings/{id}','MeetingController@show')->name('meeting.show');

});

Route::get('editmin', 'UserController@editOrg')->name('editMin');
Route::put('editmin', 'UserController@updateOrg')->name('updateOrg');
Route::get('/moveTo/{id?}','TopicController@moveTo')->name('moveTo');
Route::get('/moveToThisMeeting/{id?}/{subject_id}','TopicController@moveToThisMeeting')->name('moveToThisMeeting');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;


    class User extends Authenticatable
{
    use Notifiable;
    
    public function tasks()
    {
        return $this->hasMany('App\Task');
    }
    public function meetings()
    {
        return $this->hasMany('App\Meeting');
    }
    public function organization()
   {
       return $this->belongsTo('App\Organization', 'org_id');
   }
    public function meetingCreator()
    {
        return $this->hasMany('App\Meeting','inviter_id');
    }
    public function meetingInviteds()
    {
        return $this->belongsToMany('App\Meeting','invite');
    }
    public function topics()
    {
        return $this->hasMany('App\Topic');
    }
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role', 'organization','org_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use DB;
use App\Task;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\Hash;
use Illuminate\Http\Request;
use App\Meeting;
use App\Topic;
use App\Invite;
use App\Organization;
use Carbon\Carbon;


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\collection;//sorting, average, etc.
use Illuminate\Support\Facades\Validator;//verification

class UserController extends Controller
{
    /**
     * Display a listing of the users
     *
     * @param  \App\User  $model
     * @return \Illuminate\View\View
     */
    public function index(User $model)
    {
        $time =   NOW()->timezone('Asia/Jerusalem');
        $datas =  DB::table('users')
        ->join('tasks','tasks.user_id','=','users.id')
        ->select('tasks.task_end', 'tasks.status', 'tasks.user_id','users.id' )
       ->get();
        return view('users.index',['users' => $model->paginate(15)],compact('datas', 'time'));
    }

    /**
     * Show the form for creating a new user
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created user in storage
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\User  $model
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(UserRequest $request, User $model)
    {
        $model->create($request->merge(['password' => Hash::make($request->get('password'))])->all());

        return redirect()->route('user.index')->withStatus(__('User successfully created.'));
    }

    /**
     * Show the form for editing the specified user
     *
     * @param  \App\User  $user
     * @return \Illuminate\View\View
     */
    public function edit(User $user)
    {
        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified user in storage
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request,  $id)
    {
        $user=User::findOrFail($id);

        $user->update($request->except(['_token']));
        return redirect(route('users.index'));
        
       
    }

    /**
     * Remove the specified user from storage
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(User  $user)
    {
        $user->delete();

        return redirect()->route('user.index')->withStatus(__('User successfully deleted.'));
    }

    public function updateOrg(Request $request)
    {

             
            $this->validate(
                $request,
                [
                    'min_topic' => 'required',
                ]
            );

            $affected = DB::table('organizations')
            ->where('organization_id', Auth()->user()->org_id)
            ->update(['min_topic' => $request->min_topic]);

            return redirect()->route('user.index');

    }
    public function editOrg()
    {
        $organization = DB::table('organizations')
        ->where('organization_id', '=', Auth()->user()->org_id)->get();
            $id = Auth::user()->org_id;

            return view('users.editMin');
      
    }

}

resources/views/users/create.blade.php
@extends('layouts.app', ['title' => __('User Management')])

@section('content')
    @include('users.partials.header', ['title' => __('Add User')])   

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('User Management') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('user.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('user.store') }}" autocomplete="off">
                            @csrf
                            
                            <h6 class="heading-small text-muted mb-4">{{ __('User information') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Name') }}</label>
                                    <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Name') }}" value="{{ old('name') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-email">{{ __('Email') }}</label>
                                    <input type="email" name="email" id="input-email" class="form-control form-control-alternative{{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder="{{ __('Email') }}" value="{{ old('email') }}" required>

                                    @if ($errors->has('email'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('email') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-password">{{ __('Password') }}</label>
                                    <input type="password" name="password" id="input-password" class="form-control form-control-alternative{{ $errors->has('password') ? ' is-invalid' : '' }}" placeholder="{{ __('Password') }}" value="" required>
                                    
                                    @if ($errors->has('password'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('password') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label class="form-control-label" for="input-password-confirmation">{{ __('Confirm Password') }}</label>
                                    <input type="password" name="password_confirmation" id="input-password-confirmation" class="form-control form-control-alternative" placeholder="{{ __('Confirm Password') }}" value="" required>
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app', ['title' => __('User Management')])

@section('content')
    @include('users.partials.header', [
            'title' => __('Hello') . ' '. auth()->user()->name,
            'description' => __('On this page you can change the role of any member of your organization'),
            'class' => 'col-lg-7'
        ])       

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Edit Role') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('user.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body"> 
                    <form method="post" action="{{ route('user.update', $user) }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('put')

                          
                                <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('role') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-role">{{ __('role') }}</label>
                                <label class="form-control-label" for="role"></label>
                                    <select name="role"  id="input-role" class="form-control form-control-alternative{{ $errors->has('role') ? ' is-invalid' : '' }}" placeholder="{{ __('role') }}" value="{{ old('role', $user->role) }}" required autofocus >
                                            <option value="" selected disabled>Current Role: {{ $user->role }}</option>
                                            <option value='participant'>{{ __('Participant') }}</option>
                                            <option value='admin'>{{ __('admin') }}</option>
                                            <option value='meetingorganizer'>{{ __('Meeting Organizer') }}</option>
                                    </select>
                                    @if ($errors->has('role'))
                                       <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('role') }}</strong>
                                        </span>
                                    @endif
                                </div>


                               <div class="text-center">
                                   <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/users/editMin.blade.php
@extends('layouts.app', ['title' => __('User Profile')])

@section('content')
    @include('users.partials.header', [
        'title' => __('Hello') . ' '. auth()->user()->name,
        'description' => __('On this page, you can change the minimum number of topics that must be set when scheduling a meeting'),
        'class' => 'col-lg-7'
    ])   

    <div class="container-fluid mt--7">
        <div class="row">
            
            <div class="col-xl-8 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <h3 class="col-12 mb-0">{{ __('Edit the minimum number of topics for each meeting') }}</h3>
                        </div>
                    </div>
                    <div class="card-body">
                    <form method="post" action= "{{ route('updateOrg' )}}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('put')

                     


                            
                            <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Minimum number of topics') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('min_topic') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('min_topic') ? ' is-invalid' : '' }}" name="min_topic" id="input-min_topic" type="text" placeholder="{{ __('Minimum topics') }}" value="what is the minimum num of topics?" required />
                      @if ($errors->has('min_topic'))
                        <span id="min_topic-error" class="error text-danger" for="input-min_topic">{{ $errors->first('min_topic') }}</span>
                      @endif
                    </div>
                  </div>
                  </div>


                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app', ['title' => __('User Management')])

@section('content')
@include('users.partials.header', [
            'title' => __('Hello') . ' '. auth()->user()->name,
            'description' => __('On this page you can view all members of the organization and their role'),
            'class' => 'col-lg-7'
        ]) 

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Users') }}</h3>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{ __('Name') }}</th>
                                    <th scope="col">{{ __('Email') }}</th>
                                     <th scope="col">{{ __('role') }}</th>
                                    <th scope="col"></th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                @if($user->org_id==Auth::user()->org_id)
                                    <tr>
                                        <td>{{ $user->name }}</td>
                                        <td>
                                            <a href="mailto:{{ $user->email }}">{{ $user->email }}</a>
                                        </td>
                                       <td>{{ $user->role }}</td>
                                       <td>
                                       @foreach ($datas as $data)
                                         @if($data->task_end != null && $data->task_end < $time && $data-> user_id == $user -> id && $data->status == 0)
                                            <h3 class="mb-0">{{ __('I AM LATE') }}</h3>
                                            @break
                                        @endif
                                        @endforeach
                                       </td>
                                       
                                       @if(Auth::user()->role == 'admin')
                                        <td class="text-right">
                                       
                                            <div class="dropdown">
                                                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="fas fa-ellipsis-v"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                    <!--@if ($user->id != auth()->id())-->
                                                        <form action="{{ route('user.destroy', $user) }}" method="post">
                                                            @csrf
                                                            @method('delete')
                                                            
                                                            <a class="dropdown-item" href="{{ route('user.edit', $user) }}">{{ __('Edit') }}</a>
                                                        
                                                            <button type="button" class="dropdown-item" onclick="confirm('{{ __("Are you sure you want to delete this user?") }}') ? this.parentElement.submit() : ''">
                                                                {{ __('Delete') }}
                                                            </button>
                                                        </form>    
                                                    <!--@else-->
                                                        <a class="dropdown-item"href="{{ route('editMin') }}">{{ __('Edit') }}</a>
                                                       <!-- @endif -->
                                                    
                                                </div>
                                            </div>
                                        </td>
                                        @endif
                                    </tr>
                                    @endif
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-end" aria-label="...">
                            {{ $users->links() }}
                        </nav>
                    </div>
                </div>
            </div>
        </div>
            
        @include('layouts.footers.auth')
    </div>
@endsection