routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('meetingtasks/donet/{id}', 'TopicController@donet')->name('donet');
Route::get('tasks/done/{id}', 'TaskController@done')->name('done');
Route::resource('/meetings','MeetingController')->middleware('auth');
Route::resource('meeting', 'MeetingController');
Route::post('meeting/store', 'MeetingController@store')->name('store');
Route::get('meeting/create', 'MeetingController@create')->name('create');
Route::resource('/users','UserController')->middleware('auth');
Route::resource('users', 'UserController');
Route::resource('/organizations','OrganizationController')->middleware('auth');
Route::resource('organizations', 'OrganizationController');
Route::resource('/profile','ProfileController')->middleware('auth');
Route::resource('profile', 'ProfileController');
Route::put('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@update']);
Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
Route::put('organizations', ['as' => 'organizations.edit', 'uses' => 'OrganizationController@update']);
Route::put('organizations', ['as' => 'organizations.update', 'uses' => 'OrganizationController@update']);


Route::get('tasks/meetingTasks/{meeting_id}','TaskController@meetingTasks')->name('meetingTasks');
Route::get('/neworg', function () { return view('neworg');})->name('neworg');
Route::resource('meeting', 'MeetingController');
Route::resource('organization', 'ProfileController');
Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::put('organization', ['as' => 'organizations.edit', 'uses' => 'OrganizationController@update']);
	Route::put('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@update']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('user', ['as' => 'users.edit', 'uses' => 'UserController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	Route::get('editmin', 'UserController@editOrg')->name('editMin');
	Route::put('editMin', 'UserController@updateOrg')->name('updateOrg');
});

Route::post('/tasks/{meeting_id?}','TaskController@store')->name('store');
Route::post('/topics-store/{meeting_id?}','TopicController@store')->name('topics-store');

Route::resource('/meetings','MeetingController')->middleware('auth');
Route::resource('/tasks','TaskController')->except(['store']);
Route::resource('/topics','TopicController')->except(['store']);
Route::get('tasks/{meeting_id}','TaskController@store');
Route::get('topics/{meeting_id}','TopicController@store');

//didint go over yet
Route::group(['middleware' => 'auth'], function () {
	//Route::get('table-list', 'MeetingController@index')->name('table');
	Route::get('/dashboard', 'MeetingController@dashboard')->name('dashboard');
	Route::get('passed_meetings', 'MeetingController@passed')->name('passed_meetings');
	Route::get('notifications', 'MeetingController@tasks')->name('notifications');
	Route::get('/meetings/{id}','MeetingController@show')->name('meeting.show');

});

Route::get('editmin', 'UserController@editOrg')->name('editMin');
Route::put('editmin', 'UserController@updateOrg')->name('updateOrg');
Route::get('/moveTo/{id?}','TopicController@moveTo')->name('moveTo');
Route::get('/moveToThisMeeting/{id?}/{subject_id}','TopicController@moveToThisMeeting')->name('moveToThisMeeting');

resources/views/layouts/navbars/navbar.blade.php
@auth()
    @include('layouts.navbars.navs.auth')
@endauth
    
@guest()
    @include('layouts.navbars.navs.guest')
@endguest

resources/views/layouts/navbars/sidebar.blade.php
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        <a class="navbar-brand pt-0" href="{{ route('home') }}">
        <h1><i class="ni ni-tie-bow"></i> MeetUp  </h1>
        </a>
        <!-- User -->
        <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="media align-items-center">
                        <span class="avatar avatar-sm rounded-circle">
                        <img alt="Image placeholder" src="{{ asset('argon') }}/img/theme/team-1-800x800.jpg">
                        </span>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">{{ __('Welcome!') }}</h6>
                    </div>
                
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-settings-gear-65"></i>
                        <span>{{ __('Settings') }}</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-calendar-grid-58"></i>
                        <span>{{ __('Activity') }}</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-support-16"></i>
                        <span>{{ __('Support') }}</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                        <i class="ni ni-user-run"></i>
                        <span>{{ __('Logout') }}</span>
                    </a>
                </div>
            </li>
        </ul>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="{{ route('home') }}">
                            <img src="{{ asset('argon') }}/img/brand/blue.png">
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <!-- Form -->
            <form class="mt-4 mb-3 d-md-none">
                <div class="input-group input-group-rounded input-group-merge">
                    <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="{{ __('Search') }}" aria-label="Search">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            <span class="fa fa-search"></span>
                        </div>
                    </div>
                </div>
            </form>
            <!-- Navigation -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('home') }}">
                        <i class="ni ni-tv-2 text-primary"></i> {{ __('Dashboard') }}
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ route('meetings.index') }}">
                    <i class="fa fa-clock-o" style="color:red"></i> {{ __('meetings') }}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('tasks.index') }}">
                    <i class="fa fa-check-square-o" style="color:green"></i> {{ __('My tasks') }}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('user.index') }}">
                    <i class="fa fa-group" style="color:blue"> </i> {{ __('My organization') }} 
                    </a>
                </li>
               
     
            </ul>
        </div>
    </div>
</nav>