routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('meetingtasks/donet/{id}', 'TopicController@donet')->name('donet');
Route::get('tasks/done/{id}', 'TaskController@done')->name('done');
Route::resource('/meetings','MeetingController')->middleware('auth');
Route::resource('meeting', 'MeetingController');
Route::post('meeting/store', 'MeetingController@store')->name('store');
Route::get('meeting/create', 'MeetingController@create')->name('create');
Route::resource('/users','UserController')->middleware('auth');
Route::resource('users', 'UserController');
Route::resource('/organizations','OrganizationController')->middleware('auth');
Route::resource('organizations', 'OrganizationController');
Route::resource('/profile','ProfileController')->middleware('auth');
Route::resource('profile', 'ProfileController');
Route::put('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@update']);
Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
Route::put('organizations', ['as' => 'organizations.edit', 'uses' => 'OrganizationController@update']);
Route::put('organizations', ['as' => 'organizations.update', 'uses' => 'OrganizationController@update']);


Route::get('tasks/meetingTasks/{meeting_id}','TaskController@meetingTasks')->name('meetingTasks');
Route::get('/neworg', function () { return view('neworg');})->name('neworg');
Route::resource('meeting', 'MeetingController');
Route::resource('organization', 'ProfileController');
Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::put('organization', ['as' => 'organizations.edit', 'uses' => 'OrganizationController@update']);
	Route::put('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@update']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('user', ['as' => 'users.edit', 'uses' => 'UserController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	Route::get('editmin', 'UserController@editOrg')->name('editMin');
	Route::put('editMin', 'UserController@updateOrg')->name('updateOrg');
});

Route::post('/tasks/{meeting_id?}','TaskController@store')->name('store');
Route::post('/topics-store/{meeting_id?}','TopicController@store')->name('topics-store');

Route::resource('/meetings','MeetingController')->middleware('auth');
Route::resource('/tasks','TaskController')->except(['store']);
Route::resource('/topics','TopicController')->except(['store']);
Route::get('tasks/{meeting_id}','TaskController@store');
Route::get('topics/{meeting_id}','TopicController@store');

//didint go over yet
Route::group(['middleware' => 'auth'], function () {
	//Route::get('table-list', 'MeetingController@index')->name('table');
	Route::get('/dashboard', 'MeetingController@dashboard')->name('dashboard');
	Route::get('passed_meetings', 'MeetingController@passed')->name('passed_meetings');
	Route::get('notifications', 'MeetingController@tasks')->name('notifications');
	Route::get('/meetings/{id}','MeetingController@show')->name('meeting.show');

});

Route::get('editmin', 'UserController@editOrg')->name('editMin');
Route::put('editmin', 'UserController@updateOrg')->name('updateOrg');
Route::get('/moveTo/{id?}','TopicController@moveTo')->name('moveTo');
Route::get('/moveToThisMeeting/{id?}/{subject_id}','TopicController@moveToThisMeeting')->name('moveToThisMeeting');

app/Topic.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Topic extends Model
{
    protected $fillable =[
        'meeting_id','subject','meeting_start','meeting_end'
    ];
    public function user(){
        return $this->belongsTo('App\User');
    }

    public function meeting(){
        return $this->belongsTo('App\Meeting');
    }

}

app/Http/Controllers/TopicController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Meeting;
use App\Task;
use App\Topic;
use Illuminate\Support\Facades\Auth;

class TopicController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('topics.index')->with ('topics',Topic::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $meeting_id = $request->get('meeting_id');
         return view('topics.create')->with('meeting_id', $meeting_id);
    }

     public function moveTo($subject_id)
    {
        $subject = Topic::where('id',$subject_id)->first();
        $meeting_id=$subject->meeting_id;
        $meeting=Meeting::where('id',$meeting_id)->first();
        $organization_id= $meeting->org_id;
        return view('meetings.moveTo')->with ('meetings',Meeting::where('org_id',$organization_id)->get())->with('subject_id',$subject_id);
    }

    public function moveToThisMeeting($meeting_id,$subject_id)
    {
       $id_subject=$subject_id;
       $id_meeting= $meeting_id;
       $subject = Topic::where('id',$id_subject)->firstOrFail();
       $subject->meeting_id=$id_meeting;
       $subject->save();    
       return redirect(route('meetings.index')); 

      // return 'the subject has been move';
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store($meeting_id,Request $request)
    {
        $topic=new Topic();
        $id = Auth::id();
        $topic->meeting_id= $meeting_id;
        $topic->time_start=$request->topic_start;
        $topic->time_end=$request->topic_end;
        $topic->subject=$request->subject;
        $topic->status=0;
        $topic->save();
       
        $topics = Topic::where('meeting_id', $meeting_id)->get();
        $tasks = Task::where('meeting_id', $meeting_id)->get();
        return view('tasks.meetingTasks',compact('tasks','topics','meeting_id'));
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }


    public function donet($id)
    { 
        
        $topic = Topic::findOrFail($id);            
        $topic->status = 1; 
        $topic->save();
        $back =$topic->meeting_id;

        return redirect(route('meetingTasks',$back));    
    }  

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Topic $topic)
    {
        return view('topics.create')->with('topic', $topic);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTopicsRequest $request,Topic $topic)
    {
        $topic->save();
        return redirect(route('topics.index')); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Topic $topic)
    {
        $topic->delete();
        return redirect(route('meeting.index'))->withStatus(__('Topic successfully deleted.'));
    }
}

resources/views/topics/create.blade.php
@extends('layouts.app', ['title' => __('User Management')])

@section('content')
    @include('users.partials.header', ['title' => __('Add User')])   

   
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                               <!-- <h3 class="mb-0"> {{isset($topic)? "Edit Task Category" :"Create Task Category" }}</h3>-->
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('topics.index') }}" class="btn btn-sm btn-primary">{{ __('Show topics') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{isset($topic)?route('topics.update',$topic->id) : route('topics-store',[$meeting_id])}}" autocomplete="off">
                            @csrf
                            {{csrf_field()}}
                            @if(isset($topic))
                            @method('PUT')
                            @endif 
                            <script src="/assets/js/plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>

                            <h6 class="heading-small text-muted mb-4">{{ __('Topic') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('subject') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-subject">{{ __('Subject') }}</label>
                                    <input type="text" name="subject" id="input-subject" value="{{isset($topic) ? $topic->subject :''}}"
                                     class="form-control form-control-alternative{{ $errors->has('subject') ? ' is-invalid' : '' }}" placeholder="{{ __('Subject') }}" value="{{ old('subject') }}" required autofocus>

                                    @if ($errors->has('subject'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('subject') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                </div>


                                </div>
                                </div>
                                    <button type="submit" class="btn btn-success mt-4"> {{isset($topic)?'Update Topic' : 'Add'}}</button>
                                </div>
                            </div>
                        </form>
                                
                </div>
            
        
        @include('layouts.footers.auth')
    </div>
@endsection


<script src="/assets/js/plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>

@section('js')
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.9/js/select2.min.js"></script>
<script>
$(document).ready(function() {
    $('.js-example-basic-multiple').select2();
});
</script>
@endsection

resources/views/topics/index.blade.php
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>


@extends('layouts.app', ['title' => __('User Management')])

@section('content')
    @include('layouts.headers.cards')

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                            </div>
                            <div class="col-4 text-right">
                            @if(Auth::user()->role == 'admin')
                                <a href="{{route('topics.create')}}"  class="btn btn-sm btn-primary">{{ __('add a topik') }}</a>
                            @endif
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{ __('Subject') }}</th>
                                    <th scope="col"></th>
                                    <th scope="col"></th>
                                     <th scope="col"></th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($topics as $topic)
                                @if($topic->org_id==Auth::user()->org_id)
                                    <tr>
                                        <td><a href ="">{{$topic->subject}}</a></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td>
                                             <form action="{{ route('topic.destroy', $topic) }}" method="post">
                                                            @csrf
                                                            @method('delete')
                                                            
                                                            <a class="dropdown-item" href="{{route('',$topic->id)}}">{{ __('Edit') }}</a>
                                                        
                                                            <button type="button" class="dropdown-item" onclick="confirm('{{ __("Are you sure you want to delete this user?") }}') ? handleDelete({{$topic->id}}) : ''">
                                                                {{ __('Delete') }}
                                                            </button>
                                             </form>  
                                        </td>

                                       
                                       @if(Auth::user()->role != 'participant')
                                        <td class="text-right">
                                       
                                            <div class="dropdown">
                                                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="fas fa-ellipsis-v"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                  
                                                        <form action="{{ route('topic.destroy', $topic) }}" method="post">
                                                           
                                                            <a class="dropdown-item" href=" {{isset($topic)?'Update topic' : 'Edit New topic'}}}">{{ __('Edit') }}</a>
                                                    
                                                        </form>    
                                                    <!--@else-->
                                                        <a class="dropdown-item" href="{{ route('organization.edit') }}">{{ __('Edit') }}</a>
                                                   
                                                    
                                                </div>
                                            </div>
                                        </td>
                                        @endif
                                    </tr>
                                    @endif
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-end" aria-label="...">
                        </nav>
                    </div>
                </div>
            </div>
        </div>
            
        @include('layouts.footers.auth')
    </div>
@endsection

@section('scripts')
 <script>
  function handleDelete(id){
      var form = document.getElementById("deleteTopicForm");
      form.action= 'topics/'+ id; 
      $('#deleteModal').modal('show')
  }
 </script>
@endsection