routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('meetingtasks/donet/{id}', 'TopicController@donet')->name('donet');
Route::get('tasks/done/{id}', 'TaskController@done')->name('done');
Route::resource('/meetings','MeetingController')->middleware('auth');
Route::resource('meeting', 'MeetingController');
Route::post('meeting/store', 'MeetingController@store')->name('store');
Route::get('meeting/create', 'MeetingController@create')->name('create');
Route::resource('/users','UserController')->middleware('auth');
Route::resource('users', 'UserController');
Route::resource('/organizations','OrganizationController')->middleware('auth');
Route::resource('organizations', 'OrganizationController');
Route::resource('/profile','ProfileController')->middleware('auth');
Route::resource('profile', 'ProfileController');
Route::put('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@update']);
Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
Route::put('organizations', ['as' => 'organizations.edit', 'uses' => 'OrganizationController@update']);
Route::put('organizations', ['as' => 'organizations.update', 'uses' => 'OrganizationController@update']);


Route::get('tasks/meetingTasks/{meeting_id}','TaskController@meetingTasks')->name('meetingTasks');
Route::get('/neworg', function () { return view('neworg');})->name('neworg');
Route::resource('meeting', 'MeetingController');
Route::resource('organization', 'ProfileController');
Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::put('organization', ['as' => 'organizations.edit', 'uses' => 'OrganizationController@update']);
	Route::put('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@update']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('user', ['as' => 'users.edit', 'uses' => 'UserController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	Route::get('editmin', 'UserController@editOrg')->name('editMin');
	Route::put('editMin', 'UserController@updateOrg')->name('updateOrg');
});

Route::post('/tasks/{meeting_id?}','TaskController@store')->name('store');
Route::post('/topics-store/{meeting_id?}','TopicController@store')->name('topics-store');

Route::resource('/meetings','MeetingController')->middleware('auth');
Route::resource('/tasks','TaskController')->except(['store']);
Route::resource('/topics','TopicController')->except(['store']);
Route::get('tasks/{meeting_id}','TaskController@store');
Route::get('topics/{meeting_id}','TopicController@store');

//didint go over yet
Route::group(['middleware' => 'auth'], function () {
	//Route::get('table-list', 'MeetingController@index')->name('table');
	Route::get('/dashboard', 'MeetingController@dashboard')->name('dashboard');
	Route::get('passed_meetings', 'MeetingController@passed')->name('passed_meetings');
	Route::get('notifications', 'MeetingController@tasks')->name('notifications');
	Route::get('/meetings/{id}','MeetingController@show')->name('meeting.show');

});

Route::get('editmin', 'UserController@editOrg')->name('editMin');
Route::put('editmin', 'UserController@updateOrg')->name('updateOrg');
Route::get('/moveTo/{id?}','TopicController@moveTo')->name('moveTo');
Route::get('/moveToThisMeeting/{id?}/{subject_id}','TopicController@moveToThisMeeting')->name('moveToThisMeeting');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable =[
        'title','meeting_start','meeting_end' 
    ];

    public function user(){
        return $this->belongsTo('App\User');
    }

    public function meeting(){
        return $this->belongsTo('App\Meeting');
    }
    public function user_id()
    {
        return $this->belongsTo('App\User');
    }

}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Task;
use App\Meeting;
use App\Topic;
use App\User;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\UserRequest;
use App\Http\Requests\Tasks\CreatTaskRequests;
use App\Http\Requests\Tasks\UpdateTasksRequest;



class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = Task::where('user_id',Auth::id())->get();
        return view('tasks.index')->with ('tasks',Task::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function meetingTasks($meeting_id)
    {
       $time =  NOW()->timezone('Asia/Jerusalem');
       $id=$meeting_id;
       $meeting = Meeting::findOrFail($id); 
       $topics = Topic::where('meeting_id', $id)->get();
       $tasks = Task::where('meeting_id', $id)->get();
       $datas =  DB::table('users')
       ->join('tasks','tasks.user_id','=','users.id')
       ->select('users.id','users.name' , 'tasks.title', 'tasks.task_end', 'tasks.status', 'tasks.user_id', 'tasks.id as qs', 'tasks.meeting_id', 'tasks.creator_id' )
      ->get();
       return view('tasks.meetingTasks',compact('tasks', 'topics', 'meeting_id','datas', 'meeting', 'time'));
    } 
    
    public function done($id)
    { 
        
        $task = Task::findOrFail($id);            
        $task->status = 1; 
        $task->save();
        return redirect('tasks');    
    }   
    

    public function create(Request $request)
    {
        $meeting_id =  $request->get('meeting_id');
        return view('tasks.create' , [ 'users'=>User::all()])->with('meeting_id', $meeting_id);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store($meeting_id, Request $request)
    {
        $task=new Task();
        $id = Auth::id();
        $task->title=$request->title;
        $task->user_id=$request->user_id;
        $task->meeting_id= $meeting_id;
        $task->task_start=$request->task_start;
        $task->task_end=$request->task_end;
        $task->creator_id=$id;
        $task->status=0;
        $task->save();
        $time =   NOW()->timezone('Asia/Jerusalem');
        $id=$meeting_id;
        $meeting = Meeting::findOrFail($id); 
        $topics = Topic::where('meeting_id', $id)->get();
        $tasks = Task::where('meeting_id', $id)->get();
        $datas =  DB::table('users')
        ->join('tasks','tasks.user_id','=','users.id')
        ->select('users.id','users.name' , 'tasks.title', 'tasks.task_end', 'tasks.status', 'tasks.user_id', 'tasks.id as qs', 'tasks.meeting_id', 'tasks.creator_id' )
       ->get();
        return view('tasks.meetingTasks',compact('tasks', 'topics', 'meeting_id','datas', 'meeting', 'time'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        return view('tasks.create')->with('task', $task);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTasksRequest $request,Task $task)
    {
        $task->save();
        return redirect(route('tasks.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task, $meeting_id)
    {
        $task->delete();
        return redirect(route('meetingTasks, $meeting_id'))->withStatus(__('Task successfully deleted.'));
       
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.app', ['title' => __('User Management')])

@section('content')
    @include('users.partials.header', ['title' => __('Add Task')])   

   
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('tasks.index') }}" class="btn btn-sm btn-primary">{{ __('Show Tasks') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{route('store',[$meeting_id])}}" autocomplete="off">
                            @csrf
                            {{csrf_field()}}
                          <script src="/assets/js/plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>

                            <h6 class="heading-small text-muted mb-4">{{ __('User information') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('title') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-title">{{ __('Title') }}</label>
                                    <input type="text" name="title" id="input-title" value=""
                                     class="form-control form-control-alternative{{ $errors->has('title') ? ' is-invalid' : '' }}" placeholder="{{ __('Title') }}" value="{{ old('title') }}" required autofocus>

                                    @if ($errors->has('title'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('title') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                    <label class="form-control-label" for="task_end">{{ __('deadline') }}</label>
                                <div class="pl-lg-4">
                                    <div class="form-group{{ $errors->has('task_end') ? ' has-danger' : '' }}">
                                    <input class="form-control form-control-alternative{{ $errors->has('title') ? ' is-invalid' : '' }}"
                                    value="" name="task_end" id="task_end" type="datetime-local" placeholder="{{ __('due date') }}"  />
                                    @if ($errors->has('task_end'))
                                        <span id="date-error" class="error text-danger" for="task_end">
                                        <strong>{{ $errors->first('task_end') }}</strong>
                                        </span>
                                    @endif
                                    </div>

                                    <label class="form-control-label" for="user_id">{{ __('asign task to:') }}</label>
                                    <select class="form-control" name="user_id">
                                @foreach($users as $user)
                                        @if($user->org_id==Auth::user()->org_id )                            
                                                <option value="{{ $user->id }}">{{ $user->name }}</option>
                                        @endif
                                        @endforeach
                                            </select>   


                                </div>
                                </div>

                               
                                </div>
                                </div>
                                    <button type="submit" class="btn btn-success mt-4">
                                    {{ 'Create'}}</button>
                                </div>
                            </div>
                        </form>
                                
                </div>
            
        
        @include('layouts.footers.auth')
    </div>
@endsection


<script src="/assets/js/plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>

@section('js')
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.9/js/select2.min.js"></script>
<script>
$(document).ready(function() {
    $('.js-example-basic-multiple').select2();
});
</script>
@endsection

resources/views/tasks/index.blade.php
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>


@extends('layouts.app', ['title' => __('User Management')])

@section('content')
@include('users.partials.header', [
            'title' => __('Hello') . ' '. auth()->user()->name,
            'description' => __('On this page you can see all the tasks you are required to do and also the tasks you have assigned to other users'),
            'class' => 'col-lg-7'
        ]) 
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <h3 class="text-overflow m-0">{{ __('My tasks') }}</h3>
                            <div class="row align-items-center">
                                <div class="col-8">
                                </div>
                                <div class="col-4 text-right">
                                </div>
                            </div>
                    </div>
                    
                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>
                   
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{ __('Title') }}</th>
                                     <th scope="col">{{ __('deadline') }}</th>
                                     <th scope="col">{{ __('mark as done') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($tasks as $task)
                                    <tr>
                                @if($task->user_id==Auth::user()->id)
                                        <td>{{$task->title}}</td>
                                        <td>{{ $task->task_end }}</td>
                                        <td>  
                                            @if ($task->status == 0)
                                            <a href="{{route('done', $task->id)}}">Mark As done</a>
                                                @else
                                                    Done!
                                            @endif</td>

                                       
                                        @endif
                                    </tr>
                               
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-end" aria-label="...">
                        </nav>
                    </div>
                </div>
            </div>
        </div>
            
                <div class="col-12">
                    @if (session('status'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ session('status') }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif
                </div>
                <br>
                <br>
                @if (Auth::user()->role != 'participant')
                <div class="row">
                    <div class="col">
                        <div class="card shadow">
                            <div class="card-header border-0">
                            <h3 class="text-overflow m-0">{{ __('Tasks I have assgined') }}</h3>
                            <br>

                                <div class="table-responsive">
                                    <table class="table align-items-center table-flush">
                                        <thead class="thead-light">
                                            <tr>
                                                <th scope="col">{{ __('Title') }}</th>
                                                {{--<th scope="col">{{ __('Assigned to') }}</th>--}}
                                                <th scope="col">{{ __('Deadline') }}</th>
                                                <th scope="col">{{ __('Is it done?') }}</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($tasks as $task)
                                                <tr>
                                            @if($task->creator_id==Auth::user()->id)
                                                    <td>{{$task->title}}</td>
                                                        {{--@foreach ($users as $user)
                                                            $nameId=$task->user_id==$user->id
                                                            $name=User:where('name',$nameId)->firstOfAll();
                                                            <td>$name</td>
                                                            @endforeach
                                                        <td>{{$task->user_id}}</td>--}}
                                                    <td>{{ $task->task_end }}</td>
                                                    <td>  
                                                        @if ($task->status == 0)
                                                        {{ __('not yet') }}
                                                            @else
                                                                Done
                                                        @endif</td>

                                                    @endif
                                                </tr>
                                            
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div> 
                    </div>
                    @endif
                </div>
                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-end" aria-label="...">
                        </nav>
                    </div>
            </div>
        
        @include('layouts.footers.auth')
        </div>
    </div>
</div>
@endsection

@section('scripts')
 <script>
  function handleDelete(id){
      var form = document.getElementById("deleteTaskForm");
      form.action= 'tasks/'+ id; 
      $('#deleteModal').modal('show')
  }
 </script>
@endsection

resources/views/tasks/meetingTasks.blade.php
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>


@extends('layouts.app', ['title' => __('User Management')])

@section('content')
 @include('users.partials.header', [
            'title' => __('Hello') . ' '. auth()->user()->name,
            'description' => __('On this page you can view allsubjects and tasks of meeting'),
            'class' => 'col-lg-7'
        ]) 

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                {{--<div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                            </div>
                            <div class="col-4 text-right">
                            
                            @if(Auth::user()->role != 'participant')
                            <a href="{{route('topics.create',['meeting_id'=>$meeting_id])}}"  class="btn btn-sm btn-primary">{{ __('add a topic') }}</a>
                           @endif
                            </div>
                        </div>
                    </div> --}}
                    
                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{ __('subject') }}</th>
                                    <th scope="col"></th>
                                    <th scope="col"></th>
                                    <th scope="col"></th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($topics as $topic)
                                    <tr>
                                        <td>{{$topic->subject}}</a></td>
                                    @if(Auth::user()->role != 'participant')   
                                        <td>  
                                         @if($meeting->meeting_start < $time  && $meeting->meeting_end > $time)
                                            @if ($topic->status == 0)
                                            <a href="{{route('donet', $topic->id)}}">Mark As done</a>
                                                @else
                                                {{ __('enough with this topic') }}
                                            @endif
                                            @else
                                            <td></td>
                                        @endif</td>
                                        <td></td>
                                        <td><a href ="{{route('moveTo',$topic->id)}}" class="btn btn-info btn-sm">move to other meeting</a></td>
                                        <td>
                                            <form method="post" action ="{{action('TopicController@destroy',$topic->id)}}">
                                                @csrf
                                                @method('DELETE')
                                                <button type="button" class="dropdown-item" onclick="confirm('{{ __("Are you sure you want to delete this topic?") }}') ? this.parentElement.submit() : ''">
                                                    <input type ="submit" class=" btn btn-danger btn-sm" name="submit" value ="Delete"> 
                                                </button>
                                            </form>
                                        </td>
                                    @endif
                                    </tr>
                                    
                                @endforeach
                            </tbody>
                        </table>


    

        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                            </div>
                            <div class="col-4 text-right">
                            
                            @if(Auth::user()->role != 'participant')
                            <a href="{{route('tasks.create',['meeting_id'=>$meeting_id])}}"  class="btn btn-sm btn-primary">{{ __('add a task') }}</a>
                            @endif
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>
                        <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{ __('Task Title') }}</th>
                                    <th scope="col">{{ __('deadline') }}</th>
                                    <th scope="col">{{ __('status') }}</th>
                                     <th scope="col">{{ __('assigned to') }}</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ( $datas as $data )
                                    @if($data->creator_id == $data->id || $data->user_id == $data->id)
                                    @if($data->meeting_id == $meeting_id)
                                    <tr>
                                        <td>{{$data->title}}</a></td>
                                        @if($data->task_end != null)
                                        <td>{{$data->task_end}}</td>
                                        @else()
                                        <td></td>
                                        @endif
                                        @if($data->status == 0)
                                        <td>{{'wating to be done'}}</td>
                                        @else()
                                        <td>{{ __('done') }}</td>
                                        @endif
                                        <td>{{$data->name}}</td>
                                        <td>
                                             
                                        <td class="text-right">
                                       
                                      
                                   </td>
                                  
                                    </tr>
                                    @endif
                                    @endif
                                @endforeach
                            </tbody>
                        </table>

                        @endsection                   
@section('scripts')
    <script>
    function handleDelete(id){
        var form = document.getElementById("deleteTaskForm");
        form.action= 'tasks/'+ id; 
        console.log('deleting.',form);
        $('#deleteModal').modal('show')
    }
    
    function handleDelete(id){
        var form = document.getElementById("deleteTopicForm");
        form.action= 'topics/'+ id; 
        console.log('deleting.',form);
        $('#deleteModal').modal('show')
    }
    </script>
@endsection